fix: startup error due to missing sequelize mysql2 dep
After initial database creation when the container restarts sequelize will attempt to run migrations unsuccessfully due a missing dep `mysql2` for running in the `production` environment.

Below includes the respective error logs:

```
> heimdall@3.0.0 db:migrate /app/heimdall
> sequelize db:migrate

Sequelize CLI [Node: 14.17.6, CLI: 6.2.0, ORM: 6.6.2]

Loaded configuration file "config/database.js".
Using environment "production".

Fixing /config permissions. . .
Fixing app permissions. . .
[cont-init.d] 50-config: exited 0.
[cont-init.d] 90-custom-folders: executing...
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-files: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.

> heimdall@3.0.0 server /app/heimdall
> npm run db:migrate && node ./bin/www

> heimdall@3.0.0 db:migrate /app/heimdall
> sequelize db:migrate

Sequelize CLI [Node: 14.17.6, CLI: 6.2.0, ORM: 6.6.2]

Loaded configuration file "config/database.js".
Using environment "production".

ERROR: Please install mysql2 package manually

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! heimdall@3.0.0 db:migrate: `sequelize db:migrate`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the heimdall@3.0.0 db:migrate script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /app/heimdall/.npm/_logs/2021-09-18T02_21_48_326Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! heimdall@3.0.0 server: `npm run db:migrate && node ./bin/www`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the heimdall@3.0.0 server script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /app/heimdall/.npm/_logs/2021-09-18T02_21_48_352Z-debug.log
```